### ISSUE TITLE
Implement addition multiplication and comparison

### ISSUE THREAD

**Issue by KinanBab** [multiparty/jiff-client#3]
Must be easy to use, may require to modify share representation.

**Comment by R1issa** [comment]
Implemented addition

**Comment by KinanBab** [comment]
@R1issa the multiplication scheme is actually corrected and passed testing, however, the deferreds and promises are ruining the implementation (they are not being chained properly during multiplication). 

No more work to be done on multiplication, issue #9 is concerned with fixing the deferreds, when it is done multiplication will be complete.

comaprison is still todo.

**Comment by R1issa** [comment]
@KinanBab the multiplication is still missing the two party case. 

Comparison will rely on either one of the following papers: 
- _Multiparty Computation for Interval, Equality, and Comparison without Bit-Decomposition Protocol_, T. Nishide and K. Ohta (like in SEPIA)
- _Unconditionally secure constant-rounds multi-party computation for equality, comparison, bits and exponentiation_, I. Damgard et al.
- _Sub-Linear, Secure Comparison With Two Non-Colluding Parties,_ T. Toft (like in Viff)

Each one of these papers has some implementation of equality testing, but we should additionally consider following SEPIA's protocol which relies on Fermat's little theorem. We should also keep in mind that Viff's comparison protocol may work for jiff.

It might be useful to also look at the following paper for secure binary decomposition:
- _Efficient Binary Conversion for Paillier Encrypted Values_, Berry Schoenmakers and Pim Tuyls

We need to work on optimization techniques for comparison and equality testing because they will surely enormously slow everything down.

**Comment by KinanBab** [comment]
Fix mod and this will be done

**Comment by KinanBab** [comment]
Finally done
